// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaf-Qiv87Po5ZovXn2NQIpLKFoPNnBT9c',
    appId: '1:459959638825:web:b6a78e3304b3d8b152f538',
    messagingSenderId: '459959638825',
    projectId: 'snu-smart-city-2',
    authDomain: 'snu-smart-city-2.firebaseapp.com',
    databaseURL: 'https://snu-smart-city-2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'snu-smart-city-2.appspot.com',
    measurementId: 'G-P0PW5P3NB5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLeOOEv5Ye0v5fDWvAAXS7MDEFY5d-LWs',
    appId: '1:459959638825:android:0356ee9da1c7ad5752f538',
    messagingSenderId: '459959638825',
    projectId: 'snu-smart-city-2',
    databaseURL: 'https://snu-smart-city-2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'snu-smart-city-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcsT7XHiTbWbpWC0QLc5xulXe719-bLpA',
    appId: '1:459959638825:ios:f07ae53b12dc3dd052f538',
    messagingSenderId: '459959638825',
    projectId: 'snu-smart-city-2',
    databaseURL: 'https://snu-smart-city-2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'snu-smart-city-2.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcsT7XHiTbWbpWC0QLc5xulXe719-bLpA',
    appId: '1:459959638825:ios:ea4277eabbdad65652f538',
    messagingSenderId: '459959638825',
    projectId: 'snu-smart-city-2',
    databaseURL: 'https://snu-smart-city-2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'snu-smart-city-2.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
